"""empty message

Revision ID: 065e21c85546
Revises: f2b27d053a55
Create Date: 2022-01-03 01:11:08.806911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '065e21c85546'
down_revision = 'f2b27d053a55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cliente', 'descripcion')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cliente', sa.Column('descripcion', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
