"""empty message

Revision ID: 764e5704e0fd
Revises: 95ba1282309f
Create Date: 2021-12-29 01:56:03.742823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '764e5704e0fd'
down_revision = '95ba1282309f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contrato',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('cuidador_id', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('servicio', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['cuidador_id'], ['cuidador.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contrato')
    # ### end Alembic commands ###
