"""empty message

Revision ID: c9e6103d92e5
Revises: 065e21c85546
Create Date: 2022-01-06 18:40:52.062021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9e6103d92e5'
down_revision = '065e21c85546'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cliente', sa.Column('descripcion', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cliente', 'descripcion')
    # ### end Alembic commands ###
