"""empty message

Revision ID: f2b27d053a55
Revises: 764e5704e0fd
Create Date: 2022-01-02 23:42:21.751361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2b27d053a55'
down_revision = '764e5704e0fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cliente', 'descripcion',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cliente', 'descripcion',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
